export default [
  {
    category: 'Hats & scarves',
    popularity: 200,
    rating: 5,
    image: "img/product-image-1",
    title: "Black and white sport cap",
    currPrice: "$18.15",
    oldPrice: null,
  },
  {
    category: 'Sunglasses',
    popularity: 0,
    rating: null,
    image: "img/product-image-2",
    title: "Metal bridge sunglasses",
    currPrice: "$89.95",
    oldPrice: null,
  },
  {
    category: 'T-shirts & tops',
    popularity: 423,
    rating: 4,
    image: "img/product-image-3",
    title: "Green baby romper",
    currPrice: "$20.40",
    oldPrice: null,
  },
  {
    category: 'Jeans',
    popularity: 21,
    rating: null,
    image: "img/product-image-4",
    title: "Mid-rise slim cropped fit jeans",
    currPrice: "$40.00",
    oldPrice: null,
  },
  {
    category: 'Hair accessories',
    popularity: 1111,
    rating: 5,
    image: "img/product-image-5",
    title: "Red dangle earrings",
    currPrice: "$29.95",
    oldPrice: null,
  },
  {
    category: 'Flat shoes',
    popularity: 15,
    rating: null,
    image: "img/product-image-6",
    title: "Baby shoes with laces",
    currPrice: "$30.60",
    oldPrice: null,
  },
  {
    category: 'T-shirts & tops',
    popularity: 3920,
    rating: 5,
    image: "img/product-image-7",
    title: "Shirt with insertion lace trims",
    currPrice: "$49.95",
    oldPrice: null,
  },
  {
    category: 'Watches',
    popularity: 2010,
    rating: 4,
    image: "img/product-image-8",
    title: "Chrono watch with blue leather belt",
    currPrice: "$120.60",
    oldPrice: null,
  },
  {
    category: 'Coats',
    popularity: 24,
    rating: null,
    image: "img/product-image-9",
    title: "Check coat with colour contrast",
    currPrice: "$183.45",
    oldPrice: null,
  },
  {
    category: 'Bags & bagpacks',
    popularity: 2920,
    rating: 5,
    image: "img/product-image-10",
    title: "Leather crossbody bag with gold hardware",
    currPrice: "$89.50",
    oldPrice: "$179.00",
  },
  {
    category: 'Jeans',
    popularity: 0,
    rating: null,
    image: "img/product-image-11",
    title: "Skinny push-up jeans",
    currPrice: "$40.00",
    oldPrice: "$80.00",
  },
  {
    category: 'Heels',
    popularity: 80219,
    rating: 5,
    image: "img/product-image-12",
    title: "Wide heel suede ankle boots",
    currPrice: "$119.16",
    oldPrice: "$148.95",
  },
  {
    category: 'Sweatshirts & hoodies',
    popularity: 2322,
    rating: 4,
    image: "img/product-image-13",
    title: "Basic hooded sweatshirt in pink",
    currPrice: "$15.50",
    oldPrice: "$31.00",
  },
  {
    category: 'Sneakers',
    popularity: 54,
    rating: null,
    image: "img/product-image-14",
    title: "Men fashion gray shoes",
    currPrice: "$85.50",
    oldPrice: null,
  },
  {
    category: 'Shorts',
    popularity: 0,
    rating: null,
    image: "img/product-image-15",
    title: "Denim shorts",
    currPrice: "$20.00",
    oldPrice: '$24.00',
  },
  {
    category: 'Coats',
    popularity: 392,
    rating: 5,
    image: "img/product-image-16",
    title: "Modal-blend trenchcoat",
    currPrice: "$45.20",
    oldPrice: null,
  },
  {
    category: 'Sandals',
    popularity: 589,
    rating: 5,
    image: "img/product-image-17",
    title: "Leather sandals",
    currPrice: "$48.00",
    oldPrice: null,
  },
];
