export default {
  windowEl: window,
  documentEl: document,
  htmlEl: document.documentElement,
  bodyEl: document.body,
  headerEl: document.querySelector('.header'),
  promoSliderEl: document.querySelector('[data-promo-slider]'),
  heroSliderEl: document.querySelector('.swiper--hero'),
  arrivalsSliderEl: document.querySelector('[data-arrivals-slider]'),
  productSliderElems: document.querySelectorAll('[data-product-slider]'),
  cardSliderElems: document.querySelectorAll('.card__slider'),
  rangeSliderEl: document.querySelector('.range-slider'),
  gallerySliderEl: document.querySelector('[data-gallery-slider]'),
  thumbsSliderEl: document.querySelector('[data-thumbs-slider]'),
  tabElems: document.querySelectorAll('[data-tabs]'),
  timerEl: document.querySelector('.timer'),
  menuBtnElems: document.querySelectorAll('[data-megamenu]'),
  overlayEl: document.querySelector('[data-menu-overlay]'),
  searchInputEl: document.querySelector('[data-product-search]'),
  catalogContentEl: document.querySelector('.catalog__content'),
  filterControlEl: document.querySelector('.filter-control'),
}
